server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dashboardTemplate

  profiles:
    active: dev

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${jwt.secret}
  access-token-validity: 3600000           # 1시간 (밀리초)
  refresh-token-validity: 1209600000