server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dashboardTemplate

  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${jwt.secret}
  access-token-validity: 600000
  refresh-token-validity: 1800000

logging:
  level:
    root: INFO
    com.dashboardTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE