server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dashboardTemplate

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${jwt.secret}
  access-token-validity: 600000
  refresh-token-validity: 900000