server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: dashboardTemplate

  profiles:
    active: dev

jwt:
  secret: ${jwt.secret}
  access-token-validity: 300000
  refresh-token-validity: 600000